### ISSUE TITLE
Generate typescript artifacts containing constants representing RDF vocab terms.

### ISSUE THREAD

**Issue by MichelSc** [inrupt/artifact-generator#1029]
**Describe the bug**

Generate VocabTerms with labels and comments for iris other than classes or properties NOT working

**To Reproduce**

Use this vocabulary:
```
prd:levelVeryVeryHigh rdf:type inrupt_gen:ConstantIri ;
    rdfs:label "Very very high"@en ;
    rdfs:comment "Level very very high"@en ;
    skos:definition "http://mydomain/mypath" .    
```

1. use following generator configuration
```yaml
artifactName: vocab-bikeds
artifactGeneratorVersion: 4.0.0
artifactToGenerate:
  - programmingLanguage: TypeScript
    artifactVersion: "2.0.0"
    artifactNamePrefix: ""
    artifactNameSuffix: ""
    artifactDirectoryName: "src"
    sourceFileExtension: ts
    solidCommonVocabVersion: "^1.4.0"
    rdfjsTypesVersion: "^1.0.1"
    rdfjsImplVersion: "^1.1.0"
    supportBundling: false
    templateInternal: solidCommonVocabDependent/typescript/rdfjsRdfDataFactory/vocab.hbs

```

**Observed behavior**

I get following code generated:
```
  /**
   * Level very very high
   *
   * The term has a description only in English, with [1] label in the language [en], but [2] comments in languages [NoLocale, en] (so the difference is only between English and NoLocale, which we consider the same).
   */
  levelVeryVeryHigh: _NS("http://mydomain/mypath"),
```

NOK: labels and comments are missing

NOK: the generator crashes if the skos:definition is no valid URL

NOK: the IRI is not in the generated NamedNode

**Expected behavior**
The following code generated
```
  levelVeryVeryHigh: new _VocabTerm(
    _NS("levelVeryVeryHigh"),
    _rdfFactory,
    getLocalStore(),
    false
  )
    .addLabel(`Very very high`, "en"),
    .addComment(`Level very very high`, "en");
```
