### ISSUE TITLE
[8pt] Refactor packaging features

### ISSUE THREAD

**Issue by NSeydoux** [inrupt/artifact-generator#109]
Currently, packaging is only supported for NPM and Maven, and it is entangled with source code generation. The "definition of done" here would be:
- Artifacts information include on or several separate packaging item, looking roughly like this:
```yaml
artifactToGenerate:
  - programmingLanguage: Java
    ...
    packaging:
      - packagingTool: maven
        groupId: com.inrupt.test
        packagingFolderName: maven
        packagingTemplate: pom.hbs
      - packagingTool: gradle
        groupId: com.inrupt.test
        packagingFolderName: gradle
        packagingTemplate: build.gradle.hbs
```
- Issue #106 is resolved (groupId for java artifacts)
- Issue #86 is (at least partially) resolved (packaging templates are separate for the source code templates
- The file watcher can perform packaging
- The `generate` command supports packaging as an option
