### ISSUE TITLE
Allow users to skip packaging stage

### ISSUE THREAD

**Issue by edwardsph** [inrupt/artifact-generator#796]
**Is your feature request related to a problem? Please describe.**
When using this to generate code within another project, I am forced to configure features I do not need. I just want the source files which I then build directly into my project by adding the generated Java sources as an additional source directory in my maven project.

It is also a shame that I cannot configure the output directory (but not a major issue).

**Describe the solution you'd like**
If I am only generating source files and not an artifact or package, I would like to skip:
* `artifactName` since it is redundant (I was able to skip `artifactVersion`)
* `artifactNamePrefix`
* `artifactNameSuffix`
* `packaging`

I would also like to configure the output directory to something other than `./Generated`.

**Describe alternatives you've considered**
I added the following redundant config:
```
artifactName: cth-vocabs
artifactNamePrefix: ""
artifactNameSuffix: ""
...
    packaging:
      - packagingTool: maven
        groupId: org.solid.common.vocab
        rdf4jVersion: 4.2.2
        packagingTemplates:
          - templateInternal: rdfLibraryDependent/java/rdf4j/pom.hbs
            fileName: pom.xml
```
I then ignore the generated package files.

**Additional context**
The documentation in https://github.com/inrupt/artifact-generator/blob/main/documentation/advanced-configuration.md says:
> The packaging options are artifact-specific. They are not mandatory.

This is misleading as `packaging` is currently mandatory - I assume it is implying that no particular option is mandatory.
